# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestnewpass():
    def setup_method(self):
        self.driver = webdriver.Chrome()
        self.vars = {}
  
    def teardown_method(self):
        self.driver.quit()
  
    def test_testnewpass(self):
        self.driver.get("https://app.neapro.site/login")
        self.driver.set_window_size(1366, 736)
        self.driver.find_element(By.CSS_SELECTOR, ".fieldset:nth-child(1) input").click()
        self.driver.find_element(By.CSS_SELECTOR, ".fieldset:nth-child(1) input").send_keys("makeevaas93@yandex.ru")
        self.driver.find_element(By.CSS_SELECTOR, ".fieldset:nth-child(2) input").send_keys("Stepanova2014")
        self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
        
        time.sleep(1)
        
        element = self.driver.find_element(By.CSS_SELECTOR, ".menu-header")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()     
        self.driver.find_element(By.CSS_SELECTOR, ".avatar_link_name").click() 
        time.sleep(1)
        self.driver.find_element(By.CSS_SELECTOR, ".form-title").click()
        self.driver.find_element(By.LINK_TEXT, "Безопасность и вход").click()
        
        self.driver.find_element(By.CSS_SELECTOR, ".item:nth-child(2) .name").click()
        time.sleep(5)
        
        
        
        time.sleep(5)
        self.driver.find_element(By.CSS_SELECTOR, ".fieldset:nth-child(1) input").send_keys("makeevaas93@yandex.ru")
        
        self.driver.find_element(By.ID, "oldPassword").send_keys("Stepanova2014")
        time.sleep(5)
        
        self.driver.find_element(By.ID, "newPassword").send_keys("qwertyu1")
        time.sleep(1)
        
        self.driver.find_element(By.ID, "confirmPassword").send_keys("qwertyu1")
        time.sleep(1)
        
        self.driver.find_element(By.CSS_SELECTOR, ".fill").submit()
        
        time.sleep(1)
        
        assert self.driver.find_element(By.CSS_SELECTOR, ".body-title").text == "Пароль успешно изменен!"
        element = self.driver.find_element(By.CSS_SELECTOR, ".menu-header")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".logout > img").click()
        self.driver.find_element(By.CSS_SELECTOR, ".fieldset:nth-child(1) input").click()
        self.driver.find_element(By.CSS_SELECTOR, ".fieldset:nth-child(1) input").send_keys("makeevaas93@yandex.ru")
        self.driver.find_element(By.CSS_SELECTOR, ".fieldset:nth-child(2) input").click()
        self.driver.find_element(By.CSS_SELECTOR, ".fieldset:nth-child(2) input").send_keys("qwertyu1")
        self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".scrollmenu")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".avatar_link_name").click()
        self.driver.find_element(By.LINK_TEXT, "Безопасность и вход").click()
        self.driver.find_element(By.CSS_SELECTOR, ".item:nth-child(2) .name").click()
        self.driver.find_element(By.ID, "oldPassword").click()
        self.driver.find_element(By.ID, "oldPassword").send_keys("qwertyu1")
        self.driver.find_element(By.ID, "newPassword").send_keys("Stepanova2014")
        self.driver.find_element(By.ID, "confirmPassword").send_keys("Stepanova2014")
        self.driver.find_element(By.CSS_SELECTOR, ".fill").click()
        self.driver.find_element(By.CSS_SELECTOR, ".logout_name").click()
  
a = TestTestnewpass()
a.setup_method()
a.test_testnewpass()
a.teardown_method()
